version: "3.3"
# Указываем раздел со связанными сервисами
services:
  # Первый сервис, nginx
  nginx:
    image: nginx:latest
    # Пробрасываем порты 80 для http и 443 для https
    ports:
      - "80:80"
      - "443:443"
    # Опциональный параметр с именем контейнера
    container_name: proxy_nginx
    depends_on:
      - mongo
    volumes:
      # Используем свой nginx конфиг, он заменит дефолтный в контейнере
      - ./nginx:/etc/nginx/conf.d
      # Монтируем папку с логами на хост машину для более удобного доступа
      - ./logs:/var/log/nginx/
  # База данных , то есть mongodb
  mongo:
    container_name: mongo
    hostname: mongo
    image: mongo
    ports:
    - "27017:27017"
  nuxt:
    # Используем ранее собранный образ
    container_name: nuxt_app
    build:
      context: .
      dockerfile: ./Dockerfile-dev
    # Также пробрасываем порт на котором висит приложение
    ports:
      - "3000:3000"
