FROM node:10-alpine
ENV APP_ROOT /web
WORKDIR ${APP_ROOT}
ADD . ${APP_ROOT}
RUN apk add --update python make g++ && rm -rf /var/cache/apk/*
RUN npm install -g npm@latest
RUN npm install --save
CMD ["npm", "run", "dev"]

